#!/usr/bin/env python
# encoding: utf-8
# filename: profile.py

import pstats, cProfile

import logisticGeneral
cProfile.run('logisticGeneral.run()', 'profile.prof')
s = pstats.Stats("profile.prof")
s.sort_stats("time").print_stats()

cProfile.runctx("logisticGeneral", globals(), locals(), "Profile.prof")


s.sort_stats("time").print_stats()
s.strip_dirs().sort_stats("time").print_stats()



